# Generated by Django 3.2.9 on 2021-11-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('pages_num', models.IntegerField()),
                ('pub_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pub_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pub_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.IntegerField()),
                ('shelf_position', models.CharField(max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.book')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parent_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.copy')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.reader')),
            ],
        ),
        migrations.CreateModel(
            name='BookCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.book')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.publisher'),
        ),
        migrations.AddConstraint(
            model_name='copy',
            constraint=models.UniqueConstraint(fields=('book', 'copy_number'), name='copy_composite_workaround_uk'),
        ),
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.UniqueConstraint(fields=('reader', 'book_copy'), name='borrowing_composite_workaround_uk'),
        ),
        migrations.AddConstraint(
            model_name='bookcat',
            constraint=models.UniqueConstraint(fields=('book', 'category'), name='bookcat_composite_workaround_uk'),
        ),
    ]
